[build]
  publish = "./public"
  command = "npm run build:prod"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; connect-src 'self'; style-src 'sha256-xdFA+4D+TKFmvgPMOM87P0kVsVyLOyigB2E5LJ1kwrk='; frame-ancestors 'none'"
